.prettierignore
app.json
config/link-check/config.yml
redirects-list.json
src/components/organisms/SiteFooter/index.tsx
src/utils/shared/redirects.test.js

chore: redirects

---

content/docs/cml-with-dvc.md
content/docs/cml-with-npm.md
content/docs/start/github.md

* files were updated based on commits mentioned in #66

Match cml.dev docs with latest dvc.org cml docs

---

src/components/pages/Documentation/Layout/SearchForm/index.tsx

* updated `SearchForm` `docsearch` arguments per #68 
Fixes #68

Fix broken `SearchForm`

---

content/docs/contributing/core.md

update contrib guide

---

content/docs/start/gitlab.md

Fix typo: /varibles/variables/

---

content/docs/start/github.md

Expose access token on workflow examples

---

.github/CONTRIBUTING.md
.github/workflows/link-check-all.yml
.github/workflows/link-check-deploy.yml
.prettierignore
.restyled.yaml
README.md
config/link-check/config.yml
config/link-check/excluded-links.yml
content/docs/index.md
content/docs/self-hosted-runners.md
gatsby-config.js
package.json
redirects-list.json
yarn.lock

- includes fixing unusable/broken examples

sync with dvc.org

---

content/docs/cml-with-dvc.md
content/docs/self-hosted-runners.md
content/docs/start/github.md
content/docs/start/gitlab.md
content/docs/usage.md
content/index.mdx
src/components/pages/Home/UseCasesSection/index.tsx

This pull request aligns the documentation with https://github.com/iterative/cml/pull/489. All the double/single quote changes have been made by the Git hooks, so I guess they're fine. 🙈

Uppercase repo_token

---

content/docs/self-hosted-runners.md

The suggested environment variable has nothing to do with infrastructure provisioning and was probably copied verbatim from the DVC `remote` [documentation](https://dvc.org/doc/command-reference/remote/modify).
***
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/ …

Fix Azure credential documentation

---

content/docs/cml-with-dvc.md
content/docs/self-hosted-runners.md
content/docs/start/github.md
content/docs/start/gitlab.md
content/docs/usage.md
content/index.mdx
src/components/pages/Home/UseCasesSection/index.tsx

Update obsolete container repository names

---

content/docs/self-hosted-runners.md

Refactor cml-runner access token documentation

---

content/docs/self-hosted-runners.md

minor formatting

---

content/docs/self-hosted-runners.md

Remove GitHub-specific syntax from self-hosted runners page

---

content/docs/self-hosted-runners.md

Please refer to the commit list and messages for more information.
***
Thank you for the contribution - we'll …

Improve on-premise runners section

---

src/components/molecules/Video/index.js
src/components/organisms/SwitchableMode/Provider/index.js
src/components/organisms/SwitchableMode/Switch/index.js

* has changing of state rely on label `onClick` instead of input `onChange` 
Fixes #32

Fix broken github/gitlab toggle switch

---

content/docs/cml-with-dvc.md
content/docs/self-hosted-runners.md
content/docs/start/github.md
content/index.mdx

- `AZURE_STORAGE_CONTAINER_NAME`
- Aliy~u~n
- `[ubuntu-latest]`
- `cml-gpu` label

add missing env var, fix typos, mic linting

---

content/docs/self-hosted-runners.md
content/docs/start/github.md
content/docs/usage.md
content/index.mdx
src/components/pages/Home/UseCasesSection/index.tsx

- add gitlab self-hosted example
- minor consistency (using `cml publish`)

add GL self-hosted example

---

src/components/organisms/Page/DefaultSEO/index.tsx
src/components/organisms/SEO/index.tsx

The meta tags looked pretty good! The only issue I found was missing image alts.
Fixes #128

Update site meta tags

---

content/docs/ref/runner.md

ref/runner: 72h GH timeout

---

content/docs/ref/index.md
content/docs/ref/pr.md
content/docs/ref/publish.md
content/docs/ref/runner.md
content/docs/ref/send-comment.md
content/docs/ref/send-github-check.md
content/docs/ref/tensorboard-dev.md
content/docs/self-hosted-runners.md
package.json

ref: a real start

---

content/index.mdx
src/components/pages/Home/UseCasesSection/index.tsx

fix outdated docker images

---

src/components/molecules/HamburgerMenu/index.tsx
src/components/molecules/HamburgerMenu/styles.module.css

Forgot to add the link to doc hamburger menu!

Add MLEM link to hamburger menu

---

content/docs/contributing/core.md

- follow-up to https://github.com/iterative/cml/pull/847

contrib: update core guide

---

content/docs/self-hosted-runners.md
content/docs/start/github.md

- replaces #177
- follow-up to https://github.com/iterative/cml_base_case/pull/13
- follow-up to https://github.com/iterative/example_cml/pull/172
meta-issue: #179

add plot titles

---

content/docs/ref/runner.md

- ref/runner: clarify `--cloud-aws-security-group`
- ~`npm update`~

ref/runner: clarify `--cloud-aws-security-group`

---

content/docs/ref/runner.md

- related https://github.com/iterative/cml/issues/868

ref/runner: clarify AWS options

---

content/docs/ref/runner.md

- follow-up to https://github.com/iterative/cml/pull/861
+ fixes https://github.com/iterative/cml/issues/799

ref/runner: --docker-volumes

---

content/docs/contributing/core.md
content/docs/start/index.md
redirects-list.json
src/components/molecules/HamburgerMenu/index.tsx
src/components/organisms/SiteFooter/index.tsx
src/components/organisms/SiteHeader/index.tsx
src/components/pages/Documentation/RightPanel/index.tsx

Was a mess :see_no_evil: including dead links :skull:
Can ignore failing link-check tests since this PR adds said link.

fix discord chat links

---

content/docs/sidebar.json

ref/ci: add to sidebar

---

src/components/molecules/Paginator/styles.module.css
src/components/organisms/Page/base.css
src/components/organisms/SiteHeader/index.tsx
src/components/pages/Documentation/Layout/SidebarMenu/index.tsx
src/components/pages/Documentation/Layout/SidebarMenu/styles.module.css
src/components/pages/Documentation/Markdown/styles.module.css
src/gatsby-plugin-theme-ui/index.js
src/utils/hooks/useOnClickOutside.tsx
src/utils/hooks/useOnEscape.tsx
src/utils/hooks/usePopup.tsx
src/utils/onSelectKey.ts

Updated the current dropdown implementation with the reusable component fix for https://github.com/iterative/iterative.ai/issues/370
Also, showing a dropdown on the hover fix for https://github.com/iterative/iterative.ai/issues/390

Updated dropdown with reusable component and show on hover

---

content/docs/start/github.md
content/docs/start/gitlab.md
content/index.mdx
src/components/pages/Home/UseCasesSection/index.tsx

fix tutorial plot names

---

content/docs/ref/ci.md

Follow-up to https://github.com/iterative/cml/pull/957,
fixes https://github.com/iterative/dvc/issues/7547

ref/ci: `--unshallow`

---

content/docs/ref/ci.md

ref/ci: document --user-email --user-name

---

content/docs/ref/publish.md

ref: update `cml publish --native` documentation

---

content/docs/contributing/core.md
content/docs/install.md
content/docs/usage.md

doc: NodeJS 16

---

content/docs/start/gitlab.md

[From Discord](https://discord.com/channels/485586884165107732/728693131557732403/967137930965549066)

Fix GitLab beginners' guide

---

content/docs/cml-with-dvc.md
src/components/pages/Home/UseCasesSection/index.tsx

Closes https://github.com/iterative/cml/issues/1000 along with all the pull requests listed in https://github.com/iterative/cml/issues/1000#issuecomment-1124628318

Remove `cml publish` pipe from examples

---

src/components/pages/Home/UseCasesSection/index.tsx

drop hyphens

---

content/docs/ref/send-comment.md

ref/send-comment: PAT required for GitHub --update

---

content/docs/cml-with-dvc.md
content/docs/self-hosted-runners.md
content/docs/start/github.md
content/docs/usage.md
src/components/pages/Home/UseCasesSection/index.tsx

GitHub: checkout with head ref

---

src/components/molecules/HamburgerMenu/index.tsx
src/components/organisms/SiteFooter/index.tsx
src/components/organisms/SiteHeader/Alert/index.tsx
src/components/organisms/SiteHeader/Alert/styles.module.css
src/components/organisms/SiteHeader/index.tsx
src/gatsby-plugin-theme-ui/index.js
src/media/icons/vscode.svg

* adds to nav/footer
* adds alert

Add Info About VS Code Extension

---

content/docs/contributing/core.md
content/docs/install.md
content/docs/ref/ci.md
content/docs/ref/pr.md
content/docs/ref/publish.md
content/docs/ref/runner.md
content/docs/ref/send-comment.md
content/docs/ref/send-github-check.md
content/docs/ref/tensorboard-dev.md
content/docs/self-hosted-runners.md
content/docs/start/github.md
content/docs/start/gitlab.md
content/docs/usage.md

- use admonitions
- fix fenced blocks language
- add missing CLI ref options

docs: admonitions, fenced blocks, missing ref options

---

content/docs/ref/send-comment.md

Fix Pull Request Commit Links installation link

---

content/docs/ref/runner.md

Fixes https://github.com/iterative/cml/issues/575

add `--reuse-idle`

---

package.json

helper for docs writing

---

.husky/pre-commit
.pre-commit-hooks.yaml
package.json
src/components/molecules/Paginator/styles.module.css
src/components/organisms/Page/base.css
yarn.lock

This should help with the lint issues we've been having recently, my bad on not putting them on right in the first place!

Fix husky pre-commit linting

---

gatsby-config.js
src/components/atoms/HiddenRadioControl/index.js
src/components/atoms/ThemedGatsbyLink/index.tsx
src/components/molecules/SiteLogo/index.tsx
src/components/molecules/SubscribeSection/index.js

It Fixes the hydration issue we are getting for cml.dev.
Fixes cml.dev part of https://github.com/iterative/dvc.org/issues/3633

Hydration issue

---

content/docs/self-hosted-runners.md
content/docs/start/github.md

fix formatting

---

src/components/organisms/SiteHeader/index.tsx
src/gatsby-plugin-theme-ui/index.js

Related:
- https://github.com/iterative/dvc.org/pull/3890
- https://github.com/iterative/mlem.ai/pull/157

Add blog to navbar

---

src/components/molecules/SubscribeSection/index.js

Added hidden tags field to add Mailchimp tag (Website CML).

Add CML tag on Subscribe form

---

content/docs/contributing/core.md

Documentation for https://github.com/iterative/cml/pull/997

Update release guide for maintainers

---

content/docs/self-hosted-runners.md

This fixes secret name for PAT token in the CML runner job.

Fix secret name

---

content/docs/self-hosted-runners.md

REPO_TOKEN clarification

---

content/docs/ref/comment.md

- follow-up to https://github.com/iterative/cml/pull/1208
- follow-up to https://github.com/iterative/cml/pull/1210

ref/comment: update --publish options

---

content/docs/cml-with-dvc.md
content/docs/index.md
content/docs/ref/comment.md
content/docs/self-hosted-runners.md
content/docs/start/bitbucket.md
content/docs/start/github.md
content/docs/start/gitlab.md
content/docs/usage.md
src/components/pages/Home/UseCasesSection/index.tsx

docs: remove unneeded `--publish`

---

content/docs/self-hosted-runners.md
content/docs/start/gitlab.md
content/docs/usage.md
src/components/organisms/Tooltip/types.json
src/components/pages/Home/UseCasesSection/index.tsx

docs: fixup GitLab workflows

---

content/docs/start/bitbucket.md
content/docs/usage.md

docs: fixup Bitbucket workflows

---

content/docs/cml-with-dvc.md
content/docs/self-hosted-runners.md
content/docs/start/github.md
content/docs/usage.md
src/components/pages/Home/UseCasesSection/index.tsx

docs: fixup GitHub workflows

---

content/docs/cml-with-dvc.md
content/docs/usage.md
src/components/pages/Home/UseCasesSection/index.tsx

Also misc mods to the GitHub workflow.
In review app: https://cml-dev-cml-dvc-gitlab-amaeg4o.herokuapp.com/doc/cml-with-dvc?tab=GitLab

doc/cml-with-dvc: add GitLab

---

src/components/pages/Home/UseCasesSection/index.tsx

Add a coming soon message for Bitbucket GPU

---

content/docs/usage.md
src/components/pages/Home/UseCasesSection/index.tsx

Fix example pull request links

---

content/docs/ref/comment.md

ref/comment: --watermark-title

---

content/docs/usage.md

* Part of https://github.com/iterative/cml.dev/issues/349#issue-1415090658

Update Bitbucket "example projects" section

---

content/docs/cml-with-dvc.md

- fix wrong screenshot
- slight tidy

guide/dvc: fix gitlab

---

content/docs/self-hosted-runners.md

This is a 1-char PR.
Anything I could say in this description is debatably overkill.
Why am I still typing?
Why are you still reading?
Just click `merge` already.
End our suffering.
It's in our mutual best interest. Probably.

bump on-prem heading so it shows in right panel

---

package.json
yarn.lock

Remove gatsby-plugin-parent-resolvers

---

.devcontainer.json
.github/workflows/lint-and-test.yml
.npmrc
content/docs/ref/tensorboard.md
content/docs/self-hosted-runners.md
package.json
renovate.json
yarn.lock

Reuse renovate config(denoise)

---

src/components/molecules/HamburgerMenu/styles.module.css

This reverts commit 66f06b21ffe267fed581eef6d4e53b40ebcadc83.
Thank you for the contribution - we'll try to …

Revert "Restyled by prettier (#489)"

---

package.json
yarn.lock

Bumps our theme, updating banner for VSCode Extension Product Hunt
**Note:** To be merged by @tapadipti on product hunt launch

Update Nav Banner Text

---

content/docs/start/index.md

Fix link to GitLab getting started page

---

src/@dvcorg/gatsby-theme-iterative/components/Documentation/Layout/SearchForm/index.tsx

Closes https://github.com/iterative/itops/issues/4903

Use new search API key for Algolia

---

package.json
src/@dvcorg/gatsby-theme-iterative/components/Documentation/Layout/styles.module.css
src/@dvcorg/gatsby-theme-iterative/components/LayoutFooter/index.tsx
src/components/molecules/HamburgerMenu/styles.module.css
src/gatsby/models/github/index.js
yarn.lock

chore: upgrade pkgs
