iterative/cml.dev

README.md
content/docs/contributing/core.md
content/docs/contributing/docs.md
content/docs/sidebar.json
package.json
src/components/pages/Documentation/index.tsx

rename cml-website => cml.dev, add contrib docs

---

content/docs/index.md

Hi 👋 
- Fixed cml-with-dvc page's link.
- before: https://cml.dev/doc/use-cases
- after: https://cml.dev/doc/cml-with-dvc

Fix cml-with-dvc page's link on index.md

---

content/docs/start/github.md

It looks like that text doesn't belong to the GitHub documentation, and we still have separate sections for GitHub and GitLab. 🤔

Remove extraneous GitLab callout

---

README.md
config/link-check/excluded-links.yml
content/docs/start/index.md
src/components/organisms/SubscribeSection/Form/index.tsx

Running `link-check` (assuming https://github.com/iterative/link-check/pull/8 is merged) also yields:
- FAIL: https://dvc.us10.list-manage.com/subscribe/post?u=a08bf93caae4063c4e6a351f6&amp;id=24c0ecc49a (406)
- FAIL: https://www.linkedin.com/company/iterative-ai (999)
- FAIL: https://www.linkedin.com/company/iterative-ai (999)
- FAIL: https://sweedom.us10.list-manage.com/subscribe/post?u=a08bf93caae4063c4e6a351f6&amp;id=24c0ecc49a (406)
should they be excluded? Odd error codes (`406 not acceptable` and `999 who uses linkedin anyway`) and also 2 different mailing list links?

fix broken links

---

content/docs/self-hosted-runners.md

Follow-up of https://github.com/iterative/cml.dev/pull/90#discussion_r693111314: all the `<details>` elements included in `<h3>` headings should have `<h4>` headings for the `<summary>` part.
***
Please choose to [allow us](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to …

Convert H3 in H4 for H3 childs

---

content/docs/self-hosted-runners.md
content/docs/usage.md

- mention docker tag conventions & update cross-refs (fixes #86)
- fix broken link (related https://github.com/iterative/link-check/issues/10)

docs: docker tags

---

.eslintrc.json
src/components/organisms/SiteHeader/index.tsx

* updates our `.eslintrc.json` `overrides.files` array, adding folders that have `js` files. Otherwise we get typescript warnings on some our `js` files in `src`.
* fixes typescript errors in `src/components/organisms/SiteHeader`

Clear all `yarn lint-ts` warnings

---

content/docs/cml-with-dvc.md
content/docs/self-hosted-runners.md
content/docs/start/github.md
content/docs/start/index.md
content/docs/usage.md
content/index.mdx
src/components/pages/Home/HeroSection/index.tsx

overhaul runners, add GCP & K8s stubs

---

content/docs/self-hosted-runners.md

This PR fixes two links that lead to 404s in `self-hosted-runners.md`.

Fix URLs in self-hosted-runners

---

content/docs/ref/pr.md
content/docs/ref/publish.md
content/docs/ref/runner.md
content/docs/ref/send-comment.md
content/docs/ref/send-github-check.md
content/docs/ref/tensorboard-dev.md
content/docs/sidebar.json

Just stub pages with a little description for now. The idea (for now) is *not* to duplicate `cml {cmd} --help` output but instead provide examples, edge cases, warnings, etc.
- part of #55
- part of https://github.com/iterative/cml/issues/514

ref: first stubs

---

content/docs/index.md
src/components/pages/Documentation/Markdown/ToggleProvider/index.tsx
src/components/pages/Documentation/Markdown/index.tsx
src/components/pages/Documentation/Markdown/styles.module.css

* I went ahead and converted this pull request to draft since I placed test markdown tabs in docs/index.md.

Add markdown tabs

---

content/docs/cml-with-dvc.md
content/docs/contributing/core.md
content/docs/ref/pr.md
content/docs/ref/publish.md
content/docs/ref/send-comment.md
content/docs/ref/send-github-check.md
content/docs/ref/tensorboard-dev.md
content/docs/self-hosted-runners.md
content/docs/start/github.md
content/docs/start/gitlab.md
content/docs/start/index.md
content/docs/usage.md
content/index.mdx

- `cml-subcommand` => `cml subcommand`
- function => command
- `(my)?report.md` => `report.md`
- `(my)?(image|plot|graph).png` => `plot.png`
- fully document `cml pr` behaviour
- unify command ref summaries
- improve code snippet formatting
- minor formatting improvements
- replace command table with list (does it look better? table cell wrapping didn't work well)

cml subcommands & ref improvements

---

content/docs/self-hosted-runners.md

The example code to generate a base64 token was incorrect. `echo` adds a
trailing newline, which meant that the resulting base64 would not be a
valid basic auth header.

Fix BitBucket token instructions

---

content/docs/self-hosted-runners.md
content/docs/start/github.md

- GitHub App auth example (from https://github.com/iterative/cml/issues/800#issuecomment-970291851 @RadionBik)
- (unrelated) link to AWS creds docs
- minor copyediting

GitHub App auth example, ref AWS credentials

---

content/docs/ref/send-comment.md

Document another symptom of missing the pull request links application for BitBucket. See https://github.com/iterative/cml/pull/816 for some additional background on the error.

Document BitBucket's 'invalid or unknown installation'

---

content/docs/self-hosted-runners.md

Update https://cml.dev/doc/self-hosted-runners?tab=GitHub#app to reflect correct fine-grained GHApp permissions.
- fixes #150

update GH App perms

---

content/docs/ref/pr.md

💅 Just a few things I would find useful (i.e. I had to check for the actual implementation to find out that any pathspec is supported as `git add` is being used)

ref/pr: add options & examples

---

config/link-check/excluded-links.yml
content/docs/ref/index.md
content/docs/ref/pr.md
content/docs/ref/publish.md
content/docs/ref/runner.md
content/docs/ref/send-comment.md
content/docs/ref/send-github-check.md
content/docs/ref/tensorboard-dev.md
content/docs/sidebar.json

- add generic options index page
+ make into proper list with crosslinks/refs
- add all `cml --help` output for all commands (basic start, to replace with proper descriptions/examples in follow-up iterations)
---
- fixes https://github.com/iterative/cml/issues/361
- fixes #143
- fixes #109

ref: document all options

---

content/docs/cml-with-dvc.md
src/components/pages/Documentation/Markdown/ToggleProvider/index.tsx
src/components/pages/Documentation/Markdown/index.tsx

See nested tabs: https://cml-dev-add-nested-tabs-z82eiy.herokuapp.com/doc/cml-with-dvc
Fixes #158

Add nested tabs (up to one level)

---

content/docs/start/github.md

When I copied the example as it was, I got a YAML validation error. Using http://www.yamllint.com/ showed that the cause was on lines 10 and 12, where `env:` and `run:` were right aligned with the `:` of `name`. Left aligning these lines fixed the issue for me.

Update YAML indentation for workflow example

---

src/components/pages/Documentation/Markdown/styles.module.css

> Got a styling issue @julieg18 . Maybe someone in the web team can update the margin of the tabs section so there is some white space before the next paragraph? Currently it's gray -- looks odd:
\- @jorgeorpinel in [dvc.org#3178](https://github.com/iterative/dvc.org/pull/3178)
Already merged pr for this in dvc.org!

Add margin-bottom to toggle component

---

content/docs/ref/runner.md
content/docs/self-hosted-runners.md

- mention GCP needs zones not regions
- sync self-hosted docs with cmd ref
- add some links

runner --cloud-region: GCP zones

---

content/docs/self-hosted-runners.md
src/components/pages/Documentation/Markdown/index.tsx

This will be a simple addition to the current toggle tab on markdown. 
We can set a height through a `height` prop on the `toggle` component' `<toggle height="300px">` which will set height for all the tabs.
I have also used the prop on the `doc/self-hosted-runners` last tab which you could see once this review app is deployed.
current deployment [doc/self-hosted-runners](https://cml-dev-toggle-tab-heig-fetgnj.herokuapp.com/doc/self-hosted-runners)

height as prop for toggle component on markdown

---

src/components/atoms/Link/index.tsx
src/components/organisms/Page/utils.ts
src/utils/front/safeQuerySelector.ts

* Matching [dvc.org#3107](https://github.com/iterative/dvc.org/pull/3107), adds `safeQuerySelector` and uses it in our `Link` code.

Stop page from crashing on invalid anchor links

---

content/docs/ref/pr.md

It feels like recommending `gh` would be still useful until we address https://github.com/iterative/cml/issues/907 🤔

Document cml pr --auto-merge

---

src/components/pages/Documentation/Markdown/index.tsx
src/components/pages/Documentation/Markdown/styles.module.css

Basically a copy of [dvc.org#3371](https://github.com/iterative/dvc.org/pull/3371)
Code Example:
```
<admon type="warn">
text text text
</admon>
```
Design:
**Type options:**
* `info` (default emoji is ℹ️)
* `tip` (default emoji is 💡)
* `warn` (default emoji is ⚠️)
**Icon options:**
tip - 💡
info - ℹ️
warn - ⚠️
fire - 🔥
exclamation - ❗
beetle - 🐞

Add admonition feature

---

content/docs/ref/pr.md

Documentation stub for https://github.com/iterative/cml/pull/932; I expect reviewers (hello, reviewers) 😉 to make some substantial changes if I don't do them before they arrive.

Document `cml pr` auto–merge fallback

---

content/docs/contributing/core.md

It looks like the release managers' guide was slightly broken

Fix release managers guide

---

content/docs/cml-with-dvc.md
content/docs/contributing/core.md

- dvc: use `cml ci --unshallow`
- contrib: shorten guide (follow-up to #220)

misc minor updates

---

src/gatsby-plugin-theme-ui/components.js

#225
Quick fix for the copy to the clipboard. 
It's working fine with Chrome and FF on my end. But, Safari still fails to copy a few new lines.

fix: copy to clipboard

---

content/docs/self-hosted-runners.md

After spending time trying to implement OAuth in CML I realised that Bitbucket still supports Basic Auth using [app passwords](https://support.atlassian.com/bitbucket-cloud/docs/app-passwords/) 🤦‍♂️ 
- closes https://github.com/iterative/cml/issues/914

Bitbucket REPO_TOKEN update

---

src/components/organisms/Page/DefaultSEO/index.tsx

Updated current plausible URLs with dvc.org plausible proxy URL

Using proxy for plausible

---

content/docs/ref/runner.md
content/docs/self-hosted-runners.md

`cml runner` "Advanced" authentication options for the created instance.

---

content/docs/ref/runner.md
content/docs/self-hosted-runners.md

**Part of https://github.com/iterative/cml/pull/798#pullrequestreview-982578801**
* https://github.com/iterative/cml/pull/798#issuecomment-1135299662
* https://github.com/iterative/cml/pull/798#issuecomment-1135335406
* https://github.com/iterative/cml/pull/798#issuecomment-1135391470
> **Warning**
> The GPU example doesn't work, because of... reasons; see [iterative/cml#1015](https://github.com/iterative/cml/issues/1015)

Document `cml runner` Bitbucket support

---

content/docs/ref/send-github-check.md

Closes https://github.com/iterative/cml/issues/941 or, rather, the only actionable part of the issue.

Document `cml send-github-check` authentication

---

content/docs/ref/runner.md
content/docs/self-hosted-runners.md
yarn.lock

docs: Update GHA workflow timeout to 35 days

---

content/docs/ref/runner.md

CI is failing because of the line wrapping of this markdown file. 
Is there any particular reason it isn't this way already? I may have missed something.

Run prettier

---

content/docs/ref/pr.md

+ closes https://github.com/iterative/cml/issues/1017

Document additional `cml pr` options

---

content/docs/self-hosted-runners.md
content/docs/start/github.md
content/docs/start/gitlab.md

Updates `/doc/start/{github,gitlab}/`.
Fixes #107

update & sync getting started guides

---

.github/workflows/deployment-report.js
.github/workflows/link-check-deploy.yml
package.json
yarn.lock

See https://github.com/iterative/dvc.org/pull/3700 for more info
This will need some improvements, but solves a lot of issues as-is

Upgrade link-check to 0.12

---

content/docs/contributing/core.md
content/docs/ref/pr.md
content/docs/ref/publish.md
content/docs/ref/send-comment.md
content/docs/ref/tensorboard-dev.md
content/docs/self-hosted-runners.md
content/docs/start/github.md
content/docs/usage.md

Various spelling/grammar/formatting improvements.
This PR consolidates https://github.com/iterative/cml.dev/pull/289 https://github.com/iterative/cml.dev/pull/290 https://github.com/iterative/cml.dev/pull/291 https://github.com/iterative/cml.dev/pull/292 https://github.com/iterative/cml.dev/pull/293 https://github.com/iterative/cml.dev/pull/294 https://github.com/iterative/cml.dev/pull/295 https://github.com/iterative/cml.dev/pull/296 as requested in https://github.com/iterative/cml.dev/pull/289#issuecomment-1206529160, plus one more spelling fix (BitBucket -> Bit**b**ucket).

Improve text spelling/grammar/formatting

---

content/docs/ref/publish.md

CML counterpart of https://github.com/iterative/minroud-s3/pull/1.
Temporarily closes https://github.com/iterative/cml.dev/issues/266, will have to be rewritten as part of #316.

Document `cml publish --url`

---

config/link-check/excluded-files.yml
config/link-check/excluded-links.yml

Two links have been causing the cml.dev whole-site link check to fail, both are actually broken links, but also not really content.
- A katacoda link from the examples was causing an issue, despite us removing all katacoda links from content
- `https://dvc.org/pl/api/event` is a partial link for our Plausible proxy, so it doesn't need to stand alone as a link
Because of this, the sidebar logic file is now ignored by link check along with the exact `https://dvc.org/pl/api/event` being ignored as a link.

Exclude sidebar example and plausible API endpoint from link check

---

content/docs/cml-with-dvc.md
content/docs/ref/check.md
content/docs/ref/comment.md
content/docs/ref/index.md
content/docs/ref/pr.md
content/docs/ref/publish.md
content/docs/ref/runner.md
content/docs/ref/tensorboard-dev.md
content/docs/ref/tensorboard.md
content/docs/ref/workflow.md
content/docs/self-hosted-runners.md
content/docs/sidebar.json
content/docs/start/bitbucket.md
content/docs/start/github.md
content/docs/start/gitlab.md
content/docs/usage.md
redirects-list.json
src/components/pages/Home/UseCasesSection/index.tsx

- fixes #316
+ top-level options
+ `send-github-check` => `check create`
+ `send-comment` => `comment {create,update}`
+ `pr` => `pr create`
+ `runner` => `runner launch`
+ `tensorboard-dev` => `tensorboard connect`
+ add `workflow` stub (fixes #188)
+ drop `--rm-watermark`
+ `publish` => `comment {create,update} --publish`
+ hide `publish`
+ add `comment {create,update} [--watch,--publish-url,--native]` (fixes #266, closes #317)

document new subcommands

---

src/@dvcorg/gatsby-theme-iterative/redirects.js

The current redirects on `cml.dev` show a 404 page first instead of getting redirected from the server. I guess it's because the redirects are not preloaded. I believe preloading them would fix that.
Fixes #346 
It's working fine now: https://cml-dev-fix-redirect-gnyinegbc.herokuapp.com/chat

Fix redirects

---

content/docs/start/bitbucket.md
content/docs/start/github.md
content/docs/start/gitlab.md
content/docs/usage.md
src/components/pages/Home/HeroSection/index.tsx

Fixed a few typos. I think the "For simplicity's sake" disclaimer in the getting started can be left out, since examples are available for all three platforms.
Rewrap has made the changes look more extensive than they are.

Minor docs fixes

---

content/docs/cml-with-dvc.md
content/docs/index.md
content/docs/self-hosted-runners.md
content/docs/start/bitbucket.md
content/docs/start/github.md
content/docs/start/gitlab.md
content/docs/usage.md
src/components/pages/Home/UseCasesSection/index.tsx

- docs landing: clarify section purposes
- rename home page "CML Use Case" tab `Advanced GPU Case` -> `Runner Cloud GPU`
- tidy workflow/report section names

docs: clarify sections

---

src/gatsby/hooks/stars.ts

This PR adds a query to the stars request made by this website to use the repo for the project in question, where it currently is pulling from dvc.
https://github.com/iterative/mlem.ai/pull/206 is the same thing for mlem.ai

Fix stars pulling from DVC

---

content/docs/cml-with-dvc.md
content/docs/start/bitbucket.md
content/docs/start/github.md
content/docs/start/gitlab.md
content/docs/usage.md
src/components/pages/Home/UseCasesSection/index.tsx

To be merged against #362, may need revisiting after https://github.com/iterative/cml-examples-dev/issues/15

Suggestion: update example repositories

---

package.json

Currently, the node version is explicitly limited to less than 16.17. It prevents using the latest version. It is configured to allow higher versions.
It's already upgraded for other websites through Renovate.

Allow higher node version

---

content/docs/ref/runner.md

A bit simpler, with the same effect

Simplify SSH public key provisioning guidance

---

src/components/pages/Home/UseCasesSection/index.tsx

home: fixup bitbucket

---

content/docs/self-hosted-runners.md

self-hosted-runners: add admonitions, clarifications

---

content/docs/ref/comment.md
content/docs/ref/pr.md
content/docs/start/github.md

This also removes reference to the github checkout ref from the starting example.

Document comment target flag and provide examples.

---

content/docs/cml-with-dvc.md
content/docs/ref/comment.md
content/docs/ref/pr.md
content/docs/self-hosted-runners.md
content/docs/start/github.md
content/docs/usage.md
src/components/pages/Home/UseCasesSection/index.tsx

- purge `actions/checkout.with.ref: ${{ github.event.pull_request.head.sha }}`
- some rewording
- remove verbosity
- remove unneeded `--target=pr` flag
Follow-up to #415

docs: `comment --target` follow-up

---

content/docs/ref/comment.md
content/docs/ref/index.md
content/docs/usage.md

Remnants from https://github.com/iterative/cml.dev/pull/382/files (per https://github.com/iterative/cml.dev/pull/382#issuecomment-1461258309)

Usage: improvements

---

content/docs/self-hosted-runners.md

I recently ran into the same issue as the users in this [issue](https://github.com/iterative/cml/issues/1363#issuecomment-1459714860) and noticed that the fix was still missing from the docs.
This should fix it.

Add note about token role assignment for Gitlab

---

content/docs/ref/runner.md

This PR implements the Kubernetes arbitrary node selector described in issue https://github.com/iterative/cml/issues/1365.
This is a work in progress and my first experience with Golang and Terraform provider development, I'm open to improvements.
Related PRs:
- https://github.com/iterative/terraform-provider-iterative/pull/747
- https://github.com/iterative/cml/pull/1370

Add support for Kubernetes arbitrary node selector
